Adiciona mecanismo para o CRUD POST /articles
scieloorg/scielo_exports_doaj pull request #4
Opened 2021-12-01 21:08 UTC by patymori

#### O que esse PR faz?
Adiciona envio de artigo via HTTP POST /api/articles para exportação de documento, com tratamento de erros e retentativas para falhas de conexão e timeout.

#### Onde a revisão poderia começar?
Commit 284a540.

#### Como este poderia ser testado manualmente?
1. Instale localmente o exportador: `pip install --editable .`
2. Configure variável de ambiente `DOAJ_API_KEY`com a API KEY do DOAJ
3. Executar o exportador com o PID de um documento: `scielo-export doaj --collection <acrônimo da coleção> --pid <PID de artigo>`
4. A aplicação não deve ser interrompida por qualquer exceção HTTP

#### Algum cenário de contexto que queira dar?
O resultado da exportação está sendo definido.

### Screenshots
N/A.

#### Quais são tickets relevantes?
.

### Referências
.

2021-12-02 18:50 UTC, rafaelpezzuto requested changes
@patymori,

Fiz testes aqui e estou obtendo erro 400
![image](https://user-images.githubusercontent.com/2096125/144484524-ccdd113d-dbdd-43b7-ab7c-0509d63a35b9.png)

Procurando o significado desse erro, achei o seguinte: https://doaj.org/api/docs#!/CRUD_Articles/post_api_articles

```
Bad Request. Your request body was missing a required field, or the data in one of the fields did not match the schema above (e.g. string of latin letters in an integer field).
```

Notei que o schema esperado deve obedecer o seguinte (ignorando os campos opcionais): https://doaj.github.io/doaj-docs/master/data_models/IncomingAPIArticle

Parece que o campo "name" está um pouco diferente na nossa implementação. Porém, ajustando localmente para o formato esperado, ainda acusou erro 400.

Veja:
![image](https://user-images.githubusercontent.com/2096125/144483516-399b4c64-023b-477c-bfcb-8a7308c24fd2.png)

2021-12-03 20:49 UTC, patymori commented
> @patymori,
> 
> Fiz testes aqui e estou obtendo erro 400 ![image](https://user-images.githubusercontent.com/2096125/144484524-ccdd113d-dbdd-43b7-ab7c-0509d63a35b9.png)
> 
> Procurando o significado desse erro, achei o seguinte: https://doaj.org/api/docs#!/CRUD_Articles/post_api_articles
> 
> ```
> Bad Request. Your request body was missing a required field, or the data in one of the fields did not match the schema above (e.g. string of latin letters in an integer field).
> ```
> 
> Notei que o schema esperado deve obedecer o seguinte (ignorando os campos opcionais): https://doaj.github.io/doaj-docs/master/data_models/IncomingAPIArticle
> 
> Parece que o campo "name" está um pouco diferente na nossa implementação. Porém, ajustando localmente para o formato esperado, ainda acusou erro 400.
> 
> Veja: ![image](https://user-images.githubusercontent.com/2096125/144483516-399b4c64-023b-477c-bfcb-8a7308c24fd2.png)

Fiz a correção nos autores, adicionei outros campos e também agora estou colocando a mensagem de erro retornada no response do POST. Pode fazer o teste novamente e, caso continue dando problema, pode enviar a mensagem de exceção?

Obrigada

2021-12-03 23:22 UTC, rafaelpezzuto commented
@patymori,

Ao fazer `scielo-export --output sedo.txt doaj --collection scl --pid S0100-15742021000100200` obtenho:

```
Não foi possível exportar documento 'S0100-15742021000100200': 'Erro na exportação ao doaj: 400 Client Error: BAD REQUEST for url: https://doaj.org/api/articles. Supplied data was not valid JSON (ref: ab455010-548f-11ec-b40c-6ac132d54a90)'.
```

2021-12-04 00:58 UTC, rafaelpezzuto commented
@patymori 
estou investigando e pode ser que justamente o teste que fiz usa um PID que está associado a um ISSN não registrado no DOAJ (a app, até onde vi, está usando o eissn). No DOAJ, qualquer um dos ISSNs pode estar registrado (mas se o ISSN enviado não estiver registrado, então eles acusam erro). Vamos enviar os dois, para garantir.

Estou avaliando aqui e te conto as novidades.

2021-12-04 01:32 UTC, rafaelpezzuto commented
@patymori,

Consegui enviar um artigo fazendo um post na mão (via requests em um terminal python3) - veja o resultado em https://doaj.org/article/39b5df52bfdb44ba916dfd8087e1473f. Observei que:

1. É obrigatório enviar um `doi` (o que não é informado na documentação da API - pelo menos não encontrei essa informação) - tentei enviar sem DOI e o sistema reclamou que faltava um.
2. É preciso que o issn enviado (seja pissn ou seja eissn) esteja registrado no DOAJ. Na situação em que se envia ambos os ISSNs, se um não estiver registrado, o sistema reclama e não cria o artigo.

Sobre o envio com sucesso, veja o formato que usei:

```
# os dados em formato JSON
data = {
    "bibjson": {
        "author": [
            {
                "name": "Maria Alice Nogueira"
            }
        ],
        "identifier": [
            {
                "id": "0100-1574",
                "type": "pissn"
            },
            {
                "id": "10.1590/198053147468",
                "type": "doi"
            }
        ],
        "title": "O CAPITAL CULTURAL E A PRODUCAO DAS DESIGUALDADES ESCOLARES CONTEMPORANEAS"
    }
}

# e o post em si (k é uma string que contém a api_key da aplicação DOAJ):
requests.post("https://doaj.org/api/articles", params={"api_key": k}, json = data)
```

No entanto, testando o envio pela aplicação, o sistema ainda acusa JSON mal formado. Por fora, como indicado acima, funciona.

Outro ponto é em relação às rotas journal (pelo menos uma delas). É preciso que a nossa aplicação saiba qual é o ISSN que está registrado no DOAJ - mas isso é uma situação que não prevemos no plano. Depois vamos conversar sobre isso. 

É uma rota de busca por metadado de journal, como em: `https://doaj.org/api/search/journals/0100-1574`. Essa rota seria o suficiente, em tempo de execução, para checar se o ISSN existe na base. Mas há outras soluções, por exemplo, nós registramos (fora do contexto da aplicação em desenvolvimento), todos os ISSNs lá no DOAJ.

Havendo possibilidade, conversamos sobre as rotas journal.

2021-12-06 13:35 UTC, rafaelpezzuto commented
@patymori, 

Quando for implementar os campos opcionais, sugiro seguir a seguinte ordem:

```
1. Título # já contemplado
2. Autores # já contemplado
3. Palavras-chaves
4. Resumo
5. DOI # já contemplado
6. ISSN # já contemplado
7. Volume
8. Fascículo
```

2021-12-06 17:44 UTC, patymori commented
Olá, @rafaelpezzuto. Seguem as respostas abaixo:

> 
> Consegui enviar um artigo fazendo um post na mão (via requests em um terminal python3) - veja o resultado em https://doaj.org/article/39b5df52bfdb44ba916dfd8087e1473f. Observei que:
> 
>     1. É obrigatório enviar um `doi` (o que não é informado na documentação da API - pelo menos não encontrei essa informação) - tentei enviar sem DOI e o sistema reclamou que faltava um.

Pelo que fala na documentação: "Each of the fields is defined as laid out in the table below. All fields are optional unless otherwise specified". Se olharmos para os campos identificados com obrigatórios ou exigidos para a criação, o DOI de fato não está lá. Como será necessário para que o POST seja concluído, farei a alteração.

> 
>     2. É preciso que o issn enviado (seja pissn ou seja eissn) esteja registrado no DOAJ. Na situação em que se envia ambos os ISSNs, se um não estiver registrado, o sistema reclama e não cria o artigo.
> 

Lendo a documentação, pensei nisso.

> 
> Sobre o envio com sucesso, veja o formato que usei:
> 
> ```
> # os dados em formato JSON
> data = {
>     "bibjson": {
>         "author": [
>             {
>                 "name": "Maria Alice Nogueira"
>             }
>         ],
>         "identifier": [
>             {
>                 "id": "0100-1574",
>                 "type": "pissn"
>             },
>             {
>                 "id": "10.1590/198053147468",
>                 "type": "doi"
>             }
>         ],
>         "title": "O CAPITAL CULTURAL E A PRODUCAO DAS DESIGUALDADES ESCOLARES CONTEMPORANEAS"
>     }
> }
> 
> # e o post em si (k é uma string que contém a api_key da aplicação DOAJ):
> requests.post("https://doaj.org/api/articles", params={"api_key": k}, json = data)
> ```
> 
> No entanto, testando o envio pela aplicação, o sistema ainda acusa JSON mal formado. Por fora, como indicado acima, funciona.
> 

Vou alterar a aplicação.

> Outro ponto é em relação às rotas journal (pelo menos uma delas). É preciso que a nossa aplicação saiba qual é o ISSN que está registrado no DOAJ - mas isso é uma situação que não prevemos no plano. Depois vamos conversar sobre isso.
> 
> É uma rota de busca por metadado de journal, como em: `https://doaj.org/api/search/journals/0100-1574`. Essa rota seria o suficiente, em tempo de execução, para checar se o ISSN existe na base. Mas há outras soluções, por exemplo, nós registramos (fora do contexto da aplicação em desenvolvimento), todos os ISSNs lá no DOAJ.
> 
> Havendo possibilidade, conversamos sobre as rotas journal.

Vamos conversar sobre esse ponto do periódico sim e ver o que é melhor.

2021-12-06 19:14 UTC, patymori commented
> @patymori,
> 
> Quando for implementar os campos opcionais, sugiro seguir a seguinte ordem:
> 
> ```
> 1. Título # já contemplado
> 2. Autores # já contemplado
> 3. Palavras-chaves
> 4. Resumo
> 5. DOI # já contemplado
> 6. ISSN # já contemplado
> 7. Volume
> 8. Fascículo
> ```

Alguns desses campos são obrigatórios. Ainda assim, vou seguir a sugestão para implementar o que ainda não está implementado, OK?

2021-12-06 21:19 UTC, rafaelpezzuto commented on exporter/doaj.py
> +            "params": config.get("DOAJ_API_KEY"),
@patymori, aqui seria 
```
return {
    "params": {"api_key": config.get("DOAJ_API_KEY")},
    "json": self._data,
}
```

2021-12-07 01:46 UTC, patymori commented
@rafaelpezzuto, 

Sugiram algumas dúvidas com relação aos campos:

> 
> ```
> 3. Palavras-chaves

O DOAJ aceita até 6 palavras para descrever o documento. Eu mando de um idioma específico ou junto todas as palavras chave do documento e pego as 6 primeiras?

> ```
> 4. Resumo

Uma dúvida parecida com relação ao abstract: algum idioma específico?

2021-12-07 16:32 UTC, rafaelpezzuto reviewed
@patymori, seguem meus comentários:

1. Fiz o envio de 104 registros, porém, no output, só foi guardado o último resultado.
2. Teria como adicionar um dicionário que nós temos que mapeia cada periódico (ISSN_SciELO) ao(s) seu(s) respecitvo(s) ISSN(s) registrado(s) na base DOAJ? Com ele seria mais fácil informar o pissn e/ou o eissn de forma mais acertada.

2021-12-07 18:13 UTC, rafaelpezzuto commented
> @rafaelpezzuto,
> 
> Sugiram algumas dúvidas com relação aos campos:
> 
> > ```
> > 3. Palavras-chaves
> > ```
> 
> O DOAJ aceita até 6 palavras para descrever o documento. Eu mando de um idioma específico ou junto todas as palavras chave do documento e pego as 6 primeiras?
> 
> > ```
> > 4. Resumo
> > ```
> 
> Uma dúvida parecida com relação ao abstract: algum idioma específico?

@patymori

A questão do limite de palavras-chave aparentemente foi resolvida em maio deste ano. Veja https://github.com/DOAJ/doaj/pull/1918.

Sobre o idioma, estamos verificando.

2021-12-08 15:39 UTC, rafaelpezzuto commented
@patymori 

_1. Limite de palavras-chave_
Vi de fato que o limite de palavras-chave **não está** ativado. Portanto, não teremos problemas nesse campo.

_2. Idioma_
O DOAJ não suporta multilíngua, mas um dia suportará.
Enquanto isso não ocorre, vamos enviar os metadados em inglês, se houver.
Caso não haja (eu desconheço uma situação como essa), envia no idioma principal que houver.

_3. DOI ou fulltext link obrigatórios_
Observei que caso um código DOI não seja enviado, em seu lugar pode ser enviado um outro campo chamado "link". Algo como:

```json
"bibjson": {
    "link": {
        "type": "fulltext", 
        "content_type": "text/html", 
        "url": "https://scielo.br/.... (o link completo)",
    }
}
```

Qualquer dúvida me chama.

2021-12-08 19:41 UTC, patymori commented
Seguem as respostas:

> 
> _1. Limite de palavras-chave_ Vi de fato que o limite de palavras-chave **não está** ativado. Portanto, não teremos problemas nesse campo.
> 
> _2. Idioma_ O DOAJ não suporta multilíngua, mas um dia suportará. Enquanto isso não ocorre, vamos enviar os metadados no idioma associado ao DOI.

Vi no repositório também e já tirei a limitação e, neste caso, mandamos somente as palavras chave do idioma original (acho que é o idioma associado ao DOI)? No caso do resumo, vou enviar somente o do idioma original então.

> 
> _3. DOI ou fulltext link obrigatórios_ Observei que caso um código DOI não seja enviado, em seu lugar pode ser enviado um outro campo chamado "link". Algo como:
> 
> ```json
> "bibjson": {
>     "link": {
>         "type": "fulltext", 
>         "content_type": "text/html", 
>         "url": "https://scielo.br/.... (o link completo)",
>     }
> }
> ```

OK, vou fazer a validação para ter, ao menos, um dos dois.

2021-12-09 12:44 UTC, rafaelpezzuto approved these changes
@patymori,

Eu obtive um erro 403 (um forbidden) em alguns artigos bem específicos com a seguinte msg:

```
403 Client Error: FORBIDDEN for url ... DOI or Fulltext URL have been changed. This operation is not permitted, please contact ...)
```

Deve ter a ver com o DOI/link do artigo. Vou contactar o pessoal do DOAJ. Acho que é um problema em dados nossos que já existem lá.

Em relação ao idioma dos dados, sim, considere o idioma original (ainda que o xylose não seja confiável, pois tem situações em que há mais de um idioma original).

2021-12-09 14:38 UTC, rafaelpezzuto commented
> Vi no repositório também e já tirei a limitação e, neste caso, mandamos somente as palavras chave do idioma original (acho que é o idioma associado ao DOI)? No caso do resumo, vou enviar somente o do idioma original então.

@patymori, tanto no resumo quanto no título e nas palavras-chave.

2021-12-09 14:39 UTC, patymori commented
> 
> Eu obtive um erro 403 (um forbidden) em alguns artigos bem específicos com a seguinte msg:
> 
> ```
> 403 Client Error: FORBIDDEN for url ... DOI or Fulltext URL have been changed. This operation is not permitted, please contact ...)
> ```
> 
> Deve ter a ver com o DOI/link do artigo. Vou contactar o pessoal do DOAJ. Acho que é um problema em dados nossos que já existem lá.
> 

OK, me avise depois.

> Em relação ao idioma dos dados, sim, considere o idioma original (ainda que o xylose não seja confiável, pois tem situações em que há mais de um idioma original).

OK, vou alterar os metadados de `keywords` e envio do `abstrac` para enviar somente as do idioma original segundo o Xylose.

2021-12-13 18:22 UTC, merged