Adiciona atualização de artigos
scieloorg/scielo_exports_doaj pull request #6
Opened 2021-12-16 18:08 UTC by patymori

#### O que esse PR faz?
Adiciona funcionalidade de atualização de artigos implementando método HTTP PUT do CRUD do DOAJ para atualizar artigos. Para esta funcionalidade, também é necessário implementar o HTTP GET, pois a API do DOAJ não aceita atualizações parciais do artigo.

#### Onde a revisão poderia começar?
.

#### Como este poderia ser testado manualmente?
.

#### Algum cenário de contexto que queira dar?
.

### Screenshots
N/A.

#### Quais são tickets relevantes?
.

### Referências
.

2021-12-20 12:59 UTC, rafaelpezzuto commented
@patymori Testei aqui com alguns PIDs de distintos anos e obtive dois erros:

1. Apesar de constar que o dado foi enviado, o arquivo gravado contém apenas o termo `null`. E não consegui perceber se o dado realmente foi atualizado/enviado.
2. Para PIDs mais recentes, o sistema acusa `No DOAJ ID for article`. O que é esperado, pois não estamos mais registrando o DOAJ_ID no ArticleMeta.

Em relação ao item 2, não há muito o que fazer. Talvez seja mais efetivo buscar por DOI (pela própria API DOAJ)? Isso seria uma alteração fácil?

Em relação ao item 1, não sei o que pode estar ocorrendo.

2021-12-20 13:18 UTC, rafaelpezzuto requested changes
@patymori 

Fiz alguns testes aqui e verifiquei que ao tentar enviar um doc que já existe no DOAJ (usando export), ele acusa 403 (é esperado).

Usando o novo update, como é a ideia proposta, ele não acusa erro. Acho que está enviando de fato, porém, não consigo checar se houve update. O arquivo de saída está apenas gravand oa string `null`. O que deve ficar gravado nele?

2021-12-20 13:18 UTC, rafaelpezzuto commented on exporter/doaj.py
> +        if article.data.get("doaj_id"):
Entendo que a fonte de dados contém o dado `doaj_id`. Tudo bem quanto a isso.

Anoto aqui que é uma possibilidade não gravar os registros de doaj_id no AM (mas isso é escopo de outro projeto/trabalho).

2021-12-20 14:18 UTC, patymori commented
> @patymori Testei aqui com alguns PIDs de distintos anos e obtive dois erros:
> 
>     1. Apesar de constar que o dado foi enviado, o arquivo gravado contém apenas o termo `null`. E não consegui perceber se o dado realmente foi atualizado/enviado.
> 
>     2. Para PIDs mais recentes, o sistema acusa `No DOAJ ID for article`. O que é esperado, pois não estamos mais registrando o DOAJ_ID no ArticleMeta.
> 
> 
> Em relação ao item 2, não há muito o que fazer. Talvez seja mais efetivo buscar por DOI (pela própria API DOAJ)? Isso seria uma alteração fácil?
> 
> Em relação ao item 1, não sei o que pode estar ocorrendo.

Acabei de encontrar um problema. Vou corrigir. Quanto à busca, posso mudar sim.

2021-12-20 18:33 UTC, patymori commented
@rafaelpezzuto 

Pode, por gentileza, executar o comando adicionando `--loglevel DEBUG`. Será gerado arquivo `exporter.log`.


> @patymori
> 
> Fiz alguns testes aqui e verifiquei que ao tentar enviar um doc que já existe no DOAJ (usando export), ele acusa 403 (é esperado).
> 
> Usando o novo update, como é a ideia proposta, ele não acusa erro. Acho que está enviando de fato, porém, não consigo checar se houve update. O arquivo de saída está apenas gravand oa string `null`. O que deve ficar gravado nele?

2021-12-20 19:45 UTC, rafaelpezzuto commented
> 

Olá, segue uma saída do comando `scielo-export --loglevel DEBUG --output ~/fix.results doaj update --collection scl --pid S0011-52582019000100300`

```
2021-12-20 16:44:31,508 DEBUG [exporter.main] Executando comando "update" para PID "S0011-52582019000100300"
2021-12-20 16:44:31,914 DEBUG [urllib3.connectionpool] Starting new HTTP connection (1): articlemeta.scielo.org:80
2021-12-20 16:44:31,946 DEBUG [urllib3.connectionpool] http://articlemeta.scielo.org:80 "GET /api/v1/article?collection=scl&code=S0011-52582019000100300&format=xylose&body=false HTTP/1.1" 302 265
2021-12-20 16:44:32,684 DEBUG [urllib3.connectionpool] http://articlemeta.scielo.org:80 "GET /api/v1/article/?collection=scl&code=S0011-52582019000100300&format=xylose&body=false HTTP/1.1" 200 None
2021-12-20 16:44:32,702 DEBUG [exporter.main] Enviando requisição HTTP https://doaj.org/api/articles/1dbf550625744c78b1d55244de6316b3
2021-12-20 16:44:32,703 DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): doaj.org:443
2021-12-20 16:44:33,094 DEBUG [urllib3.connectionpool] https://doaj.org:443 "GET /api/articles/1dbf550625744c78b1d55244de6316b3?api_key=5635ac77e25b456aa6e75170e64cd78a HTTP/1.1" 200 None
2021-12-20 16:44:33,098 DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): doaj.org:443
2021-12-20 16:44:33,504 DEBUG [urllib3.connectionpool] https://doaj.org:443 "GET /api/search/journals/1678-4588 HTTP/1.1" 200 None
2021-12-20 16:44:33,506 DEBUG [exporter.main] Enviando requisição HTTP https://doaj.org/api/articles/1dbf550625744c78b1d55244de6316b3
2021-12-20 16:44:33,510 DEBUG [urllib3.connectionpool] Starting new HTTPS connection (1): doaj.org:443
2021-12-20 16:44:33,913 DEBUG [urllib3.connectionpool] https://doaj.org:443 "PUT /api/articles/1dbf550625744c78b1d55244de6316b3?api_key=5635ac77e25b456aa6e75170e64cd78a HTTP/1.1" 204 0
2021-12-20 16:44:33,915 DEBUG [exporter.main] Resultado da atualização: {'pid': 'S0011-52582019000100300', 'status': 'OK'}
2021-12-20 16:44:33,916 DEBUG [exporter.main] Gravando resultado em arquivo /home/rafaeljpd/fix.results: "{'pid': 'S0011-52582019000100300', 'status': 'OK'}"
```

2021-12-20 19:53 UTC, rafaelpezzuto commented
@patymori pelo código 204, posso entender que a solicitação de update foi bem sucedida?

2021-12-20 20:50 UTC, patymori commented
> @patymori pelo código 204, posso entender que a solicitação de update foi bem sucedida?

Exatemente, @rafaelpezzuto. Este é o código retornado pela API em caso de sucesso.

Você executou o teste semelhante no caso onde o resultado no arquivo foi salvo como `null`, somente adicionando o nível do log?

2021-12-21 00:29 UTC, rafaelpezzuto approved these changes
Pelos últimos testes que fiz funcionou bem. Quero dizer, obtive resposta 204 e o arquivo de saída não contém mais a string null e sim um json.

Apenas fiz a reinstalação com o novo código-fonte que habilitou DEBUG.

Acredito que já é possível aprovar o PR.

2021-12-21 13:21 UTC, merged